project_name: "query_100_ablation"
fold_num: 2
epochs: 30
learning_rate: 0.0001
device: "cuda"

# For ablation study
is_sampling: False
sampling_rate: 0.5
sampling_random_state: 43
sample_only_pos: False

# Query criterion
query_method: "L2"
num_query: 100