project_name: "entire-subset_30%"
fold_num: 2
epochs: 30
learning_rate: 0.0001
device: "cuda"

# For ablation study
is_sampling: True
sampling_rate: 0.3
sampling_random_state: 43
sample_only_pos: False

# Query criterion
query_method: "L2"
num_query: 20