project_name: "entire-subset_70%"
fold_num: 1
epochs: 30
learning_rate: 0.00001
device: "cuda"

# For ablation study
is_sampling: True
sampling_rate: 0.7
sampling_random_state: 42
sample_only_pos: False
