project_name: "pos-only_50%"
fold_num: 3
epochs: 30
learning_rate: 0.0001
device: "cuda"

# For ablation study
is_sampling: True
sampling_rate: 0.5
sampling_random_state: 44
sample_only_pos: True

# Query criterion
query_method: "L2"
num_query: 20