project_name: "test"
fold_num: 1
epochs: 1
learning_rate: 0.0001
device: "cuda"

# For ablation study
is_sampling: False
sampling_rate: 0.5
sampling_random_state: 42
sample_only_pos: False

# Query criterion
query_method: "Cos"
num_query: 10